### ISSUE TITLE
Getting exceptions initializing docker app.

### ISSUE THREAD

**Issue by sourabp** [alessfg/docker-openempi#2]
I am getting the following exception while initializing the docker containers using docker-compose up. 

`SEVERE: Exception fixing docBase for context [/openempi-admin]
app_1       | java.util.zip.ZipException: error in opening zip file
app_1       | 	at java.util.zip.ZipFile.open(Native Method)
app_1       | 	at java.util.zip.ZipFile.<init>(ZipFile.java:221)
app_1       | 	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
app_1       | 	at java.util.jar.JarFile.<init>(JarFile.java:154)
app_1       | 	at java.util.jar.JarFile.<init>(JarFile.java:91)
app_1       | 	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
app_1       | 	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
app_1       | 	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
app_1       | 	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
app_1       | 	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
app_1       | 	at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:111)
app_1       | 	at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:737)
app_1       | 	at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:862)
app_1       | 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:390)
app_1       | 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
app_1       | 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
app_1       | 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:388)
app_1       | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:144)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1015)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
app_1       | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
app_1       | 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:712)
app_1       | 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2002)
app_1       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
app_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
app_1       | 	at java.lang.Thread.run(Thread.java:748)
Dec 06, 2017 11:24:50 AM org.apache.catalina.core.StandardContext resourcesStart
app_1       | SEVERE: Error starting static Resources
app_1       | java.lang.IllegalArgumentException: Invalid or unreadable WAR file : error in opening zip file
app_1       | 	at org.apache.naming.resources.WARDirContext.setDocBase(WARDirContext.java:136)
app_1       | 	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:5239)
app_1       | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5430)
app_1       | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1015)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
app_1       | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
app_1       | 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:712)
app_1       | 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2002)
app_1       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
app_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
app_1       | 	at java.lang.Thread.run(Thread.java:748)
app_1       |
app_1       | Dec 06, 2017 11:24:50 AM org.apache.catalina.core.ContainerBase addChildInternal
app_1       | SEVERE: ContainerBase.addChild: start:
app_1       | org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/openempi-admin]]
app_1       | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1015)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
app_1       | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
app_1       | 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:712)
app_1       | 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2002)
app_1       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
app_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
app_1       | 	at java.lang.Thread.run(Thread.java:748)
app_1       | Caused by: org.apache.catalina.LifecycleException: Error in resourceStart()
app_1       | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5431)
app_1       | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
app_1       | 	... 10 more
app_1       |
app_1       | Dec 06, 2017 11:24:50 AM org.apache.catalina.startup.HostConfig deployDescriptor
app_1       | SEVERE: Error deploying configuration descriptor /usr/local/tomcat/conf/Catalina/localhost/openempi-admin.xml
app_1       | java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/openempi-admin]]
app_1       | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1019)
app_1       | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
app_1       | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
app_1       | 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:712)
app_1       | 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2002)
app_1       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
app_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
app_1       | 	at java.lang.Thread.run(Thread.java:748)`

Please suggest if this is due to a local configuration issue or is there something that I can fix on  my end

**Comment by moselhefnawy** [comment]
Hi @sourabp, did you solve this exception? I'm facing the same issue.
