### ISSUE TITLE
ZipException: error in opening zip file

### ISSUE THREAD

**Issue by maimas** [alessfg/docker-openempi#4]
INFO: Deploying web application archive /usr/local/tomcat/webapps/openempi-3.1.0.war
app_1       | May 17, 2018 1:41:52 AM org.apache.catalina.startup.ContextConfig beforeStart
app_1       | SEVERE: Exception fixing docBase for context [/openempi-3.1.0]
app_1       | java.util.zip.ZipException: error in opening zip file
app_1       |   at java.util.zip.ZipFile.open(Native Method)
app_1       |   at java.util.zip.ZipFile.<init>(ZipFile.java:221)
app_1       |   at java.util.zip.ZipFile.<init>(ZipFile.java:151)
app_1       |   at java.util.jar.JarFile.<init>(JarFile.java:154)
app_1       |   at java.util.jar.JarFile.<init>(JarFile.java:91)
app_1       |   at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
app_1       |   at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
app_1       |   at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
app_1       |   at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
app_1       |   at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
app_1       |   at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:111)
app_1       |   at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:727)
app_1       |   at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:852)
app_1       |   at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:390)
app_1       |   at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
app_1       |   at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
app_1       |   at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:388)
app_1       |   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:144)
app_1       |   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1017)
app_1       |   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:993)
app_1       |   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
app_1       |   at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
app_1       |   at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2021)
app_1       |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
app_1       |   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
app_1       |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
app_1       |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(T

**Comment by maimas** [comment]
Seems like the war is corrupted.

**Comment by mh11** [comment]
Seems to be an issue, that the file is stored in the `git lfs`
If Git LFS is not installed yet, please see [Git LFS](https://git-lfs.github.com) page.
First run `git lfs install` followed by `git lfs pull` in the git repository

Than you need to build the docker image again and start.
